### ISSUE TITLE
Monorepos force redundant installs

### ISSUE THREAD

**Issue by spicemix** [BBE78/cypress-sonarqube-reporter#11]
In monorepos (such as those made by `@nrwl/nx` that I am using)  the tendency is to place shared dependencies in a top-level `package.json` so they don't have to be duplicated all over the place. `cypress-sonarqube-reporter` can't find them there, because I have a cypress folder for each app in the monorepo, now each of those needs its own `node_modules` with redundant copies of `cypress-sonarqube-reporter` to install and maintain for each.

### Expected behavior

Finds `cypress-sonarqube-reporter` in any package.json/node_modules anywhere *higher* in the enclosing directories. Even if a package.json or node_modules is found, keep searching upwards in enclosing directories.

### Actual behavior
```
Could not load reporter by name: cypress-sonarqube-reporter

We searched for the reporter in these paths:
```

### Steps to reproduce the behavior

  1. Build an Nx-angular monorepo with cypress e2e
  2. Install `cypress-sonarqube-reporter` in the top level `package.json`
  3. Try to get reports working
  
Thanks for this useful tool!

**Comment by BBE78** [comment]
Hi @spicemix , thanks for your report. I have no experience on Nx so I really don't know what has to be done... By the way, the reported error `Could not load reporter by name: cypress-sonarqube-reporter` is not not raised by my tool. I suspect an error raised by Cypress.

**Comment by spicemix** [comment]
OK maybe this is a general Cypress problem. I will close for now, thanks...
