### ISSUE TITLE
Test Run Fails After First Spec Is Finished With 'could not find spec filename from title'

### ISSUE THREAD

**Issue by robin-leandro** [BBE78/cypress-sonarqube-reporter#2]
**Describe the bug**
The test run fails after the first spec file is run, with the error:
```
[cypress-sonarqube-reporter] could not find spec filename from title: {title of my file}
could not find spec filename from title: {title of my file again}
undefined
```
This does not happen when `cypress-sonarqube-reporter` is not set in `cypress.json`.
I'm using the default Cypress file structure, making a folder for each test category inside `cypress/integration/`.
The error occurs whether or not I pass arguments to `cypress-sonarqube-reporter`, using the `reporterOptions` variable in `cypress.json`. I've tried not including a `reporterOptions` at all, including an empty one and passing an `outputDir`.

**To Reproduce**
1. Installed `cypress-sonarqube-reporter`:
```
npm install --save-dev cypress-sonarqube-reporter
```
2. Run my tests with the command:
```
npx cypress run --headed --browser chrome --env configFile=dev
```
3. The test run fails after the first spec file and the error is displayed. 

**Expected behavior**
Every spec file should be ran as normal and the report should be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/29494553/71963948-4fc5c900-31c2-11ea-8e6b-c2394686bb8a.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome 79.0.3945.88
 - Cypress 3.8.1

**Additional context**
In case it's relevant, I'm the Cypress Configuration API to switch between config files as detailed [here.](https://docs.cypress.io/api/plugins/configuration-api.html#Switch-between-multiple-configuration-files)

Thanks for your help and an awesome project!

**Comment by BBE78** [comment]
Hi @robin-leandro, happy to learn that you're using this reporter. For the error raised, did you read the [Usage section](https://github.com/BBE78/cypress-sonarqube-reporter#spec-files-update) of the README that explains that you have to update your spec files? Because it seems to be the cause of your troubles...
Let me know if it's the case.

**Comment by robin-leandro** [comment]
How did I miss that, thank you much!
