### ISSUE TITLE
Request for improved documentation

### ISSUE THREAD

**Issue by stephane-tremblay5** [BBE78/cypress-sonarqube-reporter#20]
**Is your feature request related to a problem? Please describe.**
Not a problem with the code itself, but rather a documentation problem.

**Describe the solution you'd like**
I wish the documentation could be improved to better explain how to use cypress-sonarqube-reporter with Cypress and Sonarqube. I'm not exactly sure once I create the cypress.json file, how it will get picked up by Cypress or Sonarqube, or how to integrate the test results in Sonarqube.

It would be nice to have a basic end to end example either in a page or even as a video where someone does it step by step.

**Describe alternatives you've considered**
Either a example page with screenshots or an explanatory video.

**Additional context**
With the current documentation, it only explains how to create the cypress.json file, but there are no other steps explaining how to use it with Cypress or Sonarqube, which this module is supposed to integrate together.

Thank you for your time.

**Comment by BBE78** [comment]
Hi @stephane-tremblay5 , I will try to write/provide a small sample that will explain the integration with Cypress and SonarQube...

**Comment by BBE78** [comment]
Correction delivered through PR #21

**Comment by stephane-tremblay5** [comment]
Hello Benoît. My apologies for not coming back to you sooner on this. I had a very busy week.
I just want to say thank you for putting in the effort on improving the documentation. This will help greatly. I'll provide feedback if there is any need.
Have a great day!

**Comment by BBE78** [comment]
> Hello Benoît. My apologies for not coming back to you sooner on this. I had a very busy week. I just want to say thank you for putting in the effort on improving the documentation. This will help greatly. I'll provide feedback if there is any need. Have a great day!

No problem, let me know if the added example is a good start for you. Bye
