### ISSUE TITLE
test.state skipped throws error unknown test state: skipped

### ISSUE THREAD

**Issue by MCeciliaSoto** [BBE78/cypress-sonarqube-reporter#3]
**Describe the bug**
Cypress has test.state "skipped". It triggers when a before or before all hook fails.
The reporter can't manage that and stops the execution thread of all tests.

**To Reproduce**
1. Write a describe suite and a before or before all hook that fails.
2. Write it tests within the suite.
3. Run the tests.

**Actual behavior**
Execution stops with exit code 1. 
Console output:
[cypress-sonarqube-reporter] unknown test state: skipped
unknown test state: skipped

**Expected behavior**
Tests should be skipped and report should be generated.

**Additional context**
Hi, thanks for your reporting tool and its maintenance and support, it serves its purpose quite good! 

I tried to implement it in our suites and come across that error, but it was quickly fixed by adding one case more in the switch statement.

Something like this: 
```
case "skipped":
    testNode.element("skipped")
        .attribute("message", "An error occurred during a hook and remaining tests in the current suite are skipped");
    break;
```

If you want, I'd love to be a collaborator and upload this fix and help maintaining this repository for next versions on Cypress to come.

Happy testing.

**Comment by BBE78** [comment]
Hi @MCeciliaSoto, thanks for reporting your issue.
I tried to reproduce your context but I did not have the same result: Cypress raises a "failed" state and not a "skipped" state...
What is your Cypress version?

**Comment by BBE78** [comment]
I've just published a new release (even if I did not reproduce exactly your issue).
Let me know if it fixes your problem.

**Comment by MCeciliaSoto** [comment]
Oops, I forgot to add that detail. 
I now have latest 4.1.0, but I believe I saw this test.status since before (3.8.*). 

```
const specTitle = require("cypress-sonarqube-reporter/specTitle");
describe(specTitle('My Sample Test'), function() {
    before(function() {
        expect(false).to.equal(true)
    });
    it('Does not do much!', function() {
      expect(true).to.equal(true)
    })
    it('Does not do much either', function() {
        expect(2+2).to.equal(4)
    })
})
```

It fails for before, beforeEach and afterEach. 
I just notice that for a failure in after hook it throws a different error :
```
[cypress-sonarqube-reporter] the reporter "./dist/cypress/integration/sample_spec.js.xml" already exists
the reporter "./dist/cypress/integration/sample_spec.js.xml" already exists
```
Like that, twice.

**Comment by MCeciliaSoto** [comment]
Now it works like a charm! 

And about the error in after hook, it was because I was setting a test from scratch and I forgot to add the option to overwrite reports. Sorry, my bad.

**Comment by BBE78** [comment]
Good, I'm closing the issue
Thanks for using this reporter, happy testing
