### ISSUE TITLE
suite.invocationDetails incompatible when using @cypress/grep

### ISSUE THREAD

**Issue by a8trejo** [BBE78/cypress-sonarqube-reporter#45]
**Describe the bug**
When running a suite that has both cypress grep and cypress SonarQube reporter, the XML report is wrongly generated with the name `support.js.xml`, because `suite.invocationDetails` is modified when using `@cypress/grep`.

**To Reproduce**
1.  Follow the installation steps of https://www.npmjs.com/package/@cypress/grep
2.  Follow the setup and installation steps of https://github.com/BBE78/cypress-sonarqube-reporter
3.  Run `npx cypress run`

**Actual behavior**
After every spec file the invocation object is as follows:
```
invocationDetails: {
    function: 'describeGrep',
    fileUrl: 'http://localhost:3000/__cypress/tests?p=cypress/support/e2e.ts',
    originalFile: 'webpack://frontend-cypress-automation/./node_modules/@cypress/grep/src/support.js',
    relativeFile: 'node_modules/@cypress/grep/src/support.js',
    absoluteFile: '/Users/atrejop/Workspace/repos/roo/Roo-Automation/node_modules/@cypress/grep/src/support.js',
    line: 173,
    column: 0,
    whitespace: '    ',
    stack: 'Error\n' +
      '    at describeGrep (http://localhost:3000/__cypress/tests?p=cypress/support/e2e.ts:2482:7)\n' +
      '    at eval (http://localhost:3000/__cypress/tests?p=cypress/src/specs/login/login.cy.ts:755:1)\n' +
      '    at eval (http://localhost:3000/__cypress/tests?p=cypress/src/specs/login/login.cy.ts:886:3)\n' +
      '    at eval (http://localhost:3000/__cypress/tests?p=cypress/src/specs/login/login.cy.ts:888:12)\n' +
      '    at eval (<anonymous>)'
  }
```
Hence the report repeats the same name for all specs as: `support.js.xml`

**Expected behavior**
Spec names are consistent

**Possible solution**
Add this in line 41 of `node_modules/cypress-sonarqube-reporter/src/ReporterUtils.js`
```
if (typeof suite.parent.file === 'string') {
        const absolutePath = suite.invocationDetails.absoluteFile.split('cypress')[0]
        spec = options.useAbsoluteSpecPath ? `${absolutePath}${suite.parent.file}` : suite.parent.file;
    } else if (index > -1) {
```
Since the `suite.parent` object still has the actual spec's relative path

**Screenshots**
![image](https://github.com/BBE78/cypress-sonarqube-reporter/assets/62401433/ac344000-4c52-4de9-a118-43aad0b8601e)

**Comment by BBE78** [comment]
Hi @a8trejo, thanks for using my plugin on your project ;)
Did you try to change the order of declaration of these 2 plugins in Cypress? If no, could you please hav a try and let me know if it change something?
By the way, I have never used @cypress/grep plugin but it look strange to alter the invocationDetails data...

**Comment by BBE78** [comment]
Hi @a8trejo, any news?

**Comment by BBE78** [comment]
Closing the issue because no more information given in 1 year
