### ISSUE TITLE
Consider refactoring this into a Cypress plugin instead of a reporter

### ISSUE THREAD

**Issue by fcuenya** [BBE78/cypress-sonarqube-reporter#48]
**Is your feature request related to a problem? Please describe.**
I was facing the same issue as reported here https://github.com/BBE78/cypress-sonarqube-reporter/issues/46 when trying to use this reporter with component tests. I tried the forked project and while it solved the problem it made me think about how it could be solved in a more efficient way.

**Describe the solution you'd like**
The easiest way to integrate Cypress test execution reports with Sonarqube is by providing a single report file, since Sonarqube does not allow for wildcards in this particular config option.

The problem I see with the implementation of this reporter library is that it takes additional conversions between JSON and XML in order to generate this single (merged) report file, as it first generates the individual XML reports for each spec file from the Cypress JSON data and then converts them back to JSON to do the merging and finally builds the merged XML report file.

Ideally we should be able to accomplish this in one go, Cypress JSON -> XML report. This does not seem possible with a reporter, since each reporter instance gets passed the data for a single spec.

**Describe alternatives you've considered**
Alternatively, a Cypress plugin gets access to all the information about every spec run, among other things. This allows for generating a single XML report file from the Cypress JSON information in one go.

I have built such plugin, and even though it is a bit rough though (in the sense that it has some hardcoded values instead of getting them from the config options), it has been working well for my use case.

I am happy to share the code with you in case you were interested in wrappint it up (config, docs... etc) and releasing it or incorporating it to your project in any other way.

In any event, great work on this reporter. It was really helpful for me to understand how to tackle this issue and I found the code and docs really easy to follow. 

**Additional context**

**Comment by BBE78** [comment]
Hi @fcuenya, first of all many thanks for your interest on my plugin 🙂.
Good news, the problem #46 is ongoing and close to be solved. By the way, your request is a "better way" to do it (avoid multiple translations from JSON to XML, and so on): you're right.
But now I've got several points:
1. this reporter is a reporter, not really a plugin
2. a solution is provided to merge all the XML files into a single XML for a better SonarQube configuration, did you face a performance issue using it?
3. it changes (a lot) the concept of the actual reporter (should maybe renamed to "cypress-sonarqube-plugin"?)

**Comment by fcuenya** [comment]
Hey @BBE78! Answering to your (totally fair) points below:

1. 100%, I was just suggesting that using a plugin instead of a reporter seemed like a better fit for solving the actual problem (i.e. generating a SQ test report).
2. I can't say I had and I did not benchmark both approaches either. My comments were merely based on the nature of the current logic that leverages multiple conversions versus an alternative that would generate the same response in one go.
3. It does, and I am not suggesting (at all) that you drop your approach and embrace this one. Releasing it as a different project with a different name totally makes sense. 

My motivation was just to to bring up this other approach and present the opportunity to get it through the finish line, since you did such a nice job with this reporter tool and I really don't have the bandwidth to make this happen.

Feel free to reach out if you are interested and I can just paste the code here or something, since it is less than 100 lines.

Again, great job with this project!

**Comment by BBE78** [comment]
Hi @fcuenya, I close this issue since nothing will be done
