### ISSUE TITLE
Merging multiple report into one sonar.testExecutionReportPaths

### ISSUE THREAD

**Issue by PROJECTBUDDY21** [BBE78/cypress-sonarqube-reporter#5]
**Is your feature request related to a problem? Please describe.**
Hey, Thanks for the package
It is definately useful,
But there is one question
How can we merge result of multiple spec file into one and provide it to SONAR
AS sonar.testExecutionReportPaths accepts single file

**Describe the solution you'd like
Passing single file to sonar.testExecutionReportPaths

**Describe alternatives you've considered**
When multiple files are generated, merge them into single xml using some tool

**Additional context**
The Alternative method is not yet explored, but maybe you can suggest

**Comment by BBE78** [comment]
Hi @PROJECTBUDDY21,
In fact, Sonar already accepts multiple report files as described in their documentation:
> Report paths should be passed in a comma-delimited list to sonar.testExecutionReportPaths

So you should be able to do it with
`sonar.testExecutionReportPaths=report-1.xml,report-2.xml,report-3.xml`

**Comment by simonmoesorensen** [comment]
If you have a larger project where separate spec files is useful to organize tests, it would be great to have such a feature.

**Comment by lnhrdt** [comment]
@BBE78 I also think this would be very useful. On my team we're writing many tests (using the Cypress test framework) and it's error-prone for us to have to update our sonar config every time someone writes a new test. We'd like to be able to have this reporter output just one file, similar to how [jest-sonar-reporter](https://github.com/3dmind/jest-sonar-reporter) works.

Any chance that can become an option of this library?

**Comment by BBE78** [comment]
Hi @lnhrdt ! I understand what you said by "_[...] have to update our sonar config every time someone writes a new test._". To avoid these kind of troubles in my projects, I wrote scripts that generates the appropriate "sonar.properties" file according to package.json data + available reports.

@PROJECTBUDDY21 and @simonmoesorensen how did you finally do what you want?

I'm going to have a look on this feature since you're the third one...

**Comment by BBE78** [comment]
Fixed in PR #19
