### ISSUE TITLE
Handle 'empty' tests

### ISSUE THREAD

**Issue by dikkadev** [BBE78/cypress-sonarqube-reporter#55]
In our CI we have a problem with empty component tests.

A spec with a describe but without a test, results in an 'empty' report that does not adhere to spec.

**To reproduce:**
spec:
```js
describe(specTitle("The root suite"), () => {

});
```

resulting XML `none.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<testExecutions version="1">
  <file/>
</testExecutions>
```
Problems arise because there is no `path` set for the file.

**Ways to fix:**
- skip creating the XML if empty (best option IMO)
- add real path to the file
- add empty path to file

**Workaround:**
Just don't have a spec file with just an empty `describe`. (Although I think this limitation is unnecessary).

Please let me know which way of fixing this (if any) is preferred, and I'd be willing to implement the fix.

**Comment by BBE78** [comment]
Hi @Sett17, coule you please try the same empty suite but wihtout the specTitle usage ?
To verify if the created XML filename is still none.xml

**Comment by Sett17** [comment]
Yes, the `none.xml` is still created.
```js
describe("Empty suite", () => {

});
```

**Comment by BBE78** [comment]
So could you please, skip the report file generation and add a warn explaining why the report for this empty suite could not be generated?

Thx for your help 😉
