### ISSUE TITLE
bump version of fast-xml-parser to at least 4.2.5

### ISSUE THREAD

**Issue by tiimonn** [BBE78/cypress-sonarqube-reporter#58]
**Describe the bug**

fast-xml-parser's version has fixed vulnerabilities 

**To Reproduce**
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
-   OS: \[e.g. iOS]
-   Browser \[e.g. chrome, safari]
-   Version \[e.g. 22]

**Additional context**

**Comment by BBE78** [comment]
Hi @tiimonn, thanks for your PR on that issue, I've made comments on it so could you please fix them and I will provide a new version of the reporter ASAP.
Thanks !

**Comment by BBE78** [comment]
Hi @tiimonn , v1.13.1 published on NPM with this fix
