### ISSUE TITLE
Reporter not longer working

### ISSUE THREAD

**Issue by gscocozza-southworks** [BBE78/cypress-sonarqube-reporter#7]
**Description**
After the last release, the reporter is no longer working. I tried with Cypress 5.6.0, 6.0.0 & 6.0.1

**Screenshots**
_Test_
![imagen](https://user-images.githubusercontent.com/61709292/100659089-ddf0f380-332e-11eb-8570-69cbe07f7573.png)

_Before_
![imagen](https://user-images.githubusercontent.com/61709292/100659195-0a0c7480-332f-11eb-938c-7a819960a938.png)

_After_
![imagen](https://user-images.githubusercontent.com/61709292/100659218-142e7300-332f-11eb-9c98-889056236bda.png)

_Destination folder_
![imagen](https://user-images.githubusercontent.com/61709292/100659293-2e685100-332f-11eb-9acb-774f10efd18a.png)

_Config_
![imagen](https://user-images.githubusercontent.com/61709292/100659571-9323ab80-332f-11eb-9c03-4b9005292d35.png)

**Desktop:**
-   OS: Windows 10
-   Browser: Chrome
-   Version: 87

**Comment by gscocozza-southworks** [comment]
My bad, it works, but only when test are running from CLI, note from the Cypress IDE

**Comment by BBE78** [comment]
Hi @gscocozza-southworks , thanks for your feedback (you should have spent so much time to write the ticket ^^)
By the way, I've never tried my reporter with the Cypress IDE. Could be interesting to make it work within the IDE...
